# Welcoming message is now out of the game's loop
# Improved hint system, Multiple instead of one
# A Number range can be chosen by the user 
# Limited number range between 5 and 60






from hint_sys import hintsys
from hints import hint1
from hints import hint2


 # Introduction

print("Welcome to this number guessing game! Here you need to find a random number generated by the computer, you will also have a limited amount of attempts based on the difficulty you choose.")


# The game's main loop

while True: 


    import time
    import random

    time.sleep(5)
    print(" ")
    print("Please choose a difficulty :")
    print("1. Easy (10 chances)")
    print("2. Medium (5 chances)")
    print("3. Hard (3 chances)")
    print("...")
    print(" ")

    time.sleep(2)

    

    # Difficulty set

    while True:
        dif = int(input("Enter your choice : ").strip())

        if dif == 1:
            attempts = 10
            break
        elif dif == 2:
            attempts = 5
            break
        elif dif == 3:
            attempts = 3
            break
        elif dif == "":
            print("Please enter 1, 2, or 3 to choose the game difficulty")
        else:
            print("Please enter 1, 2, or 3 to choose the game difficulty")

    time.sleep(1)
    print("...")

    time.sleep(1)
    print(" ")
    time.sleep(1)

    print("Please choose a number range -> ")
    time.sleep(1)
    print(" ")

    while True:
        MIN = int(input("Your preferred minimum integer : "))
        MAX = int(input("Your preferred maximum integer : "))

        if MIN < 5 or MAX > 60:
            print("The number range is currently limited between 5 and 60, please choose accordingly.")
        else:
            print("...")
            time.sleep(1)
            print("Generating...")
            time.sleep(2)
            break

    num = random.randint(MIN, MAX)

    print("...")
    
    time.sleep(2)
    print("Thinking of a number between " + str(MIN) + " and " + str(MAX) + "...")
    print(" ")
    time.sleep(2)
    print("You have", attempts, "attempts!")
    print(" ")





    # Guessing loop 

    while attempts > 0:
        gues = input("Your guess! : ").strip()
        guess = int(gues)

        if guess == num:
            print("Winner Winner Chicken Dinner!!")
            break
        elif guess > num:
            print("It's smaller!")
        elif guess < num:
            print("It's greater!")
        elif guess == 69:
            print("I see where you are going, but that's incorrect.")

        # Limiting attempts every round
        
        attempts -= 1
        print("You have", attempts, "attempts left!")
        print(" ")

        # Hint system

        hintsys(dif, attempts, num)
        

        # Defeat message

        if attempts == 0:
            print("Out of attempts, You lose.")
            print("It was", num, "!")
            break

    print("...")

    # Retry System 
    time.sleep(2)
    u_choice = input("Do you want to try again? (N/Y): ").lower()
    time.sleep(1)
    print(" ")
    if u_choice == "n":
        print("Hope you enjoyed the game!")
        time.sleep(2)
        break




